# Generated by Django 5.1.4 on 2026-02-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='is_weekly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
