# Generated by Django 5.1.4 on 2026-02-11 06:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_created_at_task_is_weekly_task_time_slot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_weekly',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('MAIN', 'Main Quest'), ('SIDE', 'Side Quest')], default='MAIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
