# Generated by Django 5.1.4 on 2026-02-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_is_completed_weeklyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_slot',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
